### ISSUE TITLE
ImportError: cannot import name MetricKeys

### ISSUE THREAD

**Issue by quxiaofeng** [polyaxon/polyaxon#24]
In Ubuntu 16.04.2, using tensorflow 1.3.0, when "import polyaxon", this error occurs.

```bash
# python -c "import polyaxon"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/polyaxon/__init__.py", line 6, in <module>
    from . import models
  File "/usr/local/lib/python2.7/dist-packages/polyaxon/models/__init__.py", line 6, in <module>
    from polyaxon.models.base import BaseModel
  File "/usr/local/lib/python2.7/dist-packages/polyaxon/models/base.py", line 8, in <module>
    from polyaxon.estimators.estimator_spec import EstimatorSpec
  File "/usr/local/lib/python2.7/dist-packages/polyaxon/estimators/__init__.py", line 7, in <module>
    from polyaxon.estimators.estimator import Estimator
  File "/usr/local/lib/python2.7/dist-packages/polyaxon/estimators/estimator.py", line 19, in <module>
    from tensorflow.python.estimator.model_fn import MetricKeys
ImportError: cannot import name MetricKeys

```

**Comment by mouradmourafiq** [comment]
Yes currently the version in pypi (0.0.3) does not work with tensorflow 1.3.0, you should install tensorflow 1.2.1.

On the other hand, the problem is fixed on master currently. The API is a bit different though, since a lot has been refactored.

**Comment by quxiaofeng** [comment]
@mouradmourafiq Thanks. I will try with different settings, either tf 1.2.1, or the master branch.

**Comment by quxiaofeng** [comment]
Tried the master branch with tf 1.3.0, succeeded.
