### ISSUE TITLE
Investigate issue with mpl_to_plotly not working with matplotlib-3.3.0

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#940]
### Describe the bug

Logging matplotlib-3.3.0 figures to Plotly raises an exception:
```
AttributeError: 'Spine' object has no attribute 'is_frame_like'
```

**Comment by mouradmourafiq** [comment]
Seems like more people are having similar issue: https://github.com/plotly/plotly.py/issues/1568

**Comment by mouradmourafiq** [comment]
I think as a workaround we can patch the utility with this code that was removed: https://github.com/anntzer/matplotlib/blob/9536fe9a83731d9172ff06b12957181974f12dd7/lib/matplotlib/spines.py#L181 until there's a fix in plotly.
